### ISSUE TITLE
[Simulator] Window is blank in macOS Mojave

### ISSUE THREAD

**Issue by tjhorner** [numworks/epsilon#688] opened 2018-09-26 18:53 UTC
**Edit:** Workaround [here](
https://github.com/numworks/epsilon/issues/688#issuecomment-425256801).

Cleaning and then running `make PLATFORM=simulator` against the latest `master` (at the time of writing, 9a1ecec3229d0cbc5e9820eebbd3ae2c9198c60e) then opening up `epsilon.elf` from a terminal gives a blank window on macOS Mojave (18A391). This might be a FLTK issue, but I'm not really sure. Here's how it looks:

<img width="452" alt="image" src="https://user-images.githubusercontent.com/2646487/46102206-a1d80c00-c182-11e8-896e-720460914540.png">

It remains this way with dark mode both on and off.

**Comment by ItsDaGeek** [comment] 2018-09-27 06:01
Unable to reproduce issue on macOS High Sierra (10.13.4 17E199) with commit 9a1ecec. I wouldn't be surprised if this is an issue with FLTK.
![image](https://user-images.githubusercontent.com/15151345/46125909-fc538580-c1df-11e8-89f0-0302df26df3e.png)

**Comment by adriweb** [comment] 2018-09-27 15:48
Can confirm that on Mojave, it's blank.
In both normal and Dark system theme, btw.

Probably fltk indeed...

**Comment by tjhorner** [comment] 2018-09-27 22:00
For reference, here is the relevant issue on fltk.org: http://www.fltk.org/str.php?L3496+P0+S0+C0+I0+E0+V%25+Qmojave

One user on the issue there says `r.13057` fixes the issue. (Relevant commit: https://github.com/fltk/fltk/commit/f76d2a2bf8c35c0c313f05bbd6deda49dd344efc)

Here is a workaround until the fix is released:

0. Remove any existing versions of FLTK
  `brew uninstall fltk`
1. Clone FLTK source repo
  `git clone https://github.com/fltk/fltk.git`
2. Go into FLTK directory
  `cd fltk`
3. Checkout commit w/ Mojave fix
  `git checkout f76d2a2bf8c35c0c313f05bbd6deda49dd344efc`
4. Build and install
  `make clean && make install`
5. Go back into your epsilon directory and rebuild
  `make PLATFORM=simulator clean && make PLATFORM=simulator`

Works for me on the latest Mojave beta build (18B45d). Although, I think we should keep this issue open until FLTK releases the fix in a stable version of the library just in case anyone else runs into this issue with the epsilon simulator.

**Comment by Ecco** [comment] 2018-10-04 09:48
Thank you very much for the investigation @tjhorner ! I'll close this issue since its not directly in our code 😄

**Closed by Ecco** 2018-10-04 09:48 UTC

**Comment by Ecco** [comment] 2018-10-29 14:21
See Homebrew/homebrew-core#33342
