### ISSUE TITLE
Disable polar complex output on real results

### ISSUE THREAD

**Issue by AndreasET** [numworks/epsilon#1398] opened 2020-03-11 19:04 UTC
#### Problem you'd like to fix
It's kind of unexpected and hard to read, if the result is negative (real) when complex format is set to polar.

#### Screenshots
![screenshot (6)](https://user-images.githubusercontent.com/39586213/76452788-f9e3ec00-63d1-11ea-9374-0e8c252526ae.png)

#### Describe the solution you'd like
Only make use of complex display if the result is complex. 
When the calculator is in Cartesian mode, it won't output '+i*0' either.

#### Describe alternatives you've considered
An additional function to convert between cartesian and polar might
do this as well, if one stays in cartesian mode, but it won't be that intuitive.
(Such a function should have been implemented per se)

**Comment by artaxxx** [comment] 2020-04-07 12:37
The idea of the polar mode is to provide all the results in polar form. Even the real ones. I think this mode is the same on other models. So this is not a bug.
Your idea to add a function "cartesian<>polar" is good. As it is mentioned in another issue, I'm closing yours.

**Closed by artaxxx** 2020-04-07 12:37 UTC
Labels: enhancement
