### ISSUE TITLE
Cannot solve the equation when the interval is too big

### ISSUE THREAD

**Issue by weathon** [numworks/epsilon#1739] opened 2020-12-28 17:31 UTC
![image](https://user-images.githubusercontent.com/41298844/103232307-bc6c3300-48ff-11eb-987a-622060e19722.png)
Type this into the calculator

Set the interval to 0-100
![image](https://user-images.githubusercontent.com/41298844/103232394-f1788580-48ff-11eb-808c-4b0ad90d88e2.png)

It will come with a result
![image](https://user-images.githubusercontent.com/41298844/103232413-fb9a8400-48ff-11eb-81bd-e5681f33c63a.png)

But if the interval is too big
![image](https://user-images.githubusercontent.com/41298844/103232366-dc035b80-48ff-11eb-9a49-1b0b43f41fb0.png)

No result found
![image](https://user-images.githubusercontent.com/41298844/103232509-3b616b80-4900-11eb-86a8-6ad1b13b58b7.png)

**Comment by RedGl0w** [comment] 2020-12-29 06:57
Note : duplicate of #1567

**Closed** 2020-12-30 18:11 UTC
