### ISSUE TITLE
Can't set the default language

### ISSUE THREAD

**Issue by ljoets** [numworks/epsilon#964] opened 2019-04-26 07:31 UTC
Hi,
I want to set french as default language when launching the simulator.
I build epsilon.elf (on Debian Stretch) and epsilon.exe (on windows 7) files as described here : https://www.numworks.com/resources/engineering/software/sdk/, but when launching them with --language fr parameter as proposed here : https://github.com/numworks/epsilon/issues/963 The calculator still appear in english.
What's wrong ?
Thanks

**Comment by RedGl0w** [comment] 2020-08-05 08:27
The issue is that with theses [lines](https://github.com/numworks/epsilon/blob/edafa0e15555bdd024660e78e36756651bd85438/ion/src/simulator/shared/main_sdl.cpp#L24-L28), when you start the simulator with `--language fr`, the simulator will be in fr, but just after, if a default language is detected on the host, the simulator will change to the other one. Instead of `push_back`, the language should be added, but in first position.

**Comment by RedGl0w** [comment] 2021-05-05 19:09
Fixed with https://github.com/numworks/epsilon/commit/79985a019938b94a81f3de27bdc7262441b42aaf (I think)

**Closed** 2021-07-22 12:58 UTC
Labels: platform-simulator, runtime-bug
