### ISSUE TITLE
Arcos, Arcsin, Arctan lag

### ISSUE THREAD

**Issue by RedGl0w** [numworks/epsilon#867] opened 2019-01-18 13:53 UTC
When I use arcos, arcsin or arctan, there's some lag, which can be very long !

**Comment by artaxxx** [comment] 2019-01-18 15:51
Could you give an example please?

**Comment by RedGl0w** [comment] 2019-01-18 17:03
if you make a lot of arcsin,not on emulator, you go to the menu, and you come back to the calculation mode, the calculator will lag.
I don't know if it's "normal" and not a bug, but it was pretty long

**Comment by DSchndr** [comment] 2019-01-19 10:05
Can confirm this, enter arcsin with some value and go to homescreen, when you go back to calculation it takes some time.

**Comment by LeJoW** [comment] 2019-01-19 10:11
With the beta version 10.0.0, I cannot reproduce this …

**Comment by RedGl0w** [comment] 2019-01-19 10:32
I was on 9.2.0

**Comment by EmilieNumworks** [comment] 2019-01-21 09:33
This was slow on the 1.8 and 9.2 versions but was fixed on the beta 10.0 version.

**Closed by EmilieNumworks** 2019-01-21 09:33 UTC
