### ISSUE TITLE
Issues with master (c84216d)

### ISSUE THREAD

**Issue by boricj** [numworks/epsilon#952] opened 2019-04-06 18:13 UTC
#### Describe the bug
I'm running into issues trying to use the latest master with the device target (c84216d):
* The `openocd.cfg` file is missing `gdb_memory_map disable` to make OpenOCD work with my ST-Link v2.
* With standard build, the device is stuck on the on-boarding screen.
* With `EPSILON_ONBOARDING_APP=0`, the device is stuck on the home menu.
* The firmware doesn't seem stuck through SWD probing. The calculator switches to the DFU screen upon plugging and leaves it upon hitting Back/unplugging, but nothing else makes it budge.

I can build, flash and use version 10.1.0 (commit id 48c088) with no issues.

#### Screenshots
N/A.

#### To Reproduce
1. Build the latest master (c84216d).
2. Flash it to a calculator.

#### Expected behavior
A working master device build.

#### Environment
 - Epsilon commit id c84216d (affected)
 - Epsilon version 10.1.0, commit id 48c088 (not affected)
 - Debian 9.8 (build host)

**Comment by creikey** [comment] 2019-04-07 20:37
I'm getting the same issues on an ArchLinux build host. When I push master firmware and try to exit the connected screen, the screen glitches back and forth between the connected and splash screen

**Comment by creikey** [comment] 2019-04-07 20:38
On the simulator there is no issue on master branch.

**Comment by creikey** [comment] 2019-04-09 01:13
I'm guessing that some fixes for the bugs were rolled out in version-10 but weren't in the master branch, so I'm merging the `version-10` branch into master right now.

**Comment by creikey** [comment] 2019-04-10 23:16
@Ecco I'm not sure if this is `infra` as it's glitching on runtime

**Comment by creikey** [comment] 2019-04-11 02:01
Ok so, I successfully merged `master` and `v-10`, and the issue is still present.

**Comment by creikey** [comment] 2019-04-11 02:03
A possible source of the issue could be that when flashing the `master`'s firmware it doesn't ask me to reset the calculator, might be something wrong with the DFU.

**Comment by Ecco** [comment] 2019-04-17 09:40
> @Ecco I'm not sure if this is `infra` as it's glitching on runtime

You're right indeed.

**Closed** 2019-04-17 11:51 UTC
Labels: bug
