### ISSUE TITLE
[feature request] Programmer mode app

### ISSUE THREAD

**Issue by Vechus** [numworks/epsilon#750] opened 2018-11-03 14:30 UTC
It's a thing that I and many other people would find very useful: an app that lets you compute numbers in base 16, 2, 8 and 10 and shows them on a simple table like in the windows calculator app.

Hope that you like this idea, you're doing a great job in developing epsilon 😄

**Comment by adriweb** [comment] 2018-11-03 16:31
Base conversion in general was/is a requested feature, actually, and was (semi-?)implemented here: https://github.com/numworks/epsilon/pull/163
In fact, it's also missing on some of the competitor models, while it's getting more and more useful for students... Probably a good idea to have it rather sooner than later :)

The table aspect of your proposal is new I guess, but the base conversion one was talked about here already: https://github.com/numworks/epsilon/issues/133

**Comment by Ecco** [comment] 2019-10-07 18:12
I think this is pretty much a duplicate of #133 so I'm going to close it as such.

**Closed by Ecco** 2019-10-07 18:12 UTC
