### ISSUE TITLE
Systems of equations with linear-solvable solutions can be incorrectly marked as nonlinear

### ISSUE THREAD

**Issue by MixedMatched** [numworks/epsilon#1718] opened 2020-11-23 23:21 UTC
#### Screenshots
![Screenshot_20201123-180920_NumWorks](https://user-images.githubusercontent.com/30960626/100026101-269d2f80-2db8-11eb-825d-eee310f66280.jpg)
![Screenshot_20201123-180925_NumWorks](https://user-images.githubusercontent.com/30960626/100026096-256c0280-2db8-11eb-8a6b-cc740b480067.jpg)

#### To Reproduce
1. Go to the equations app
2. Create a system of equations with a nonlinear equation, but a linear solution
3. Try to solve

#### Expected behavior
The equations app should, in this case, give an answer that x=5, y=5, and z=15, which can be solved by linearly solving for x in the lower two equations and substituting it in in the nonlinear equation.

#### Environment
 - Mainline Epsilon 14.4.1
 - Android App

**Comment by Ecco** [comment] 2020-11-24 02:22
Thanks for the report! At the moment we only solve linear equation systems, and simply error-out on non-linear systems.

In your example, you inputed a non-linear system. Yes, it's a very simple system, and yes, it could easily be solved. But it's a special case that's pretty trivial. The problem is that solving an *arbitrary* non-linear system is a whole other story.

I'm going to close this issue because the software works as intended.

**Closed by Ecco** 2020-11-24 02:22 UTC
