### ISSUE TITLE
Input derivatives in standard mathematical notation instead of 'diff(f(x), x, a)' format

### ISSUE THREAD

**Issue by mbokinala** [numworks/epsilon#1833] opened 2021-04-25 20:58 UTC
#### Problem you'd like to fix
When entering a derivative in the Calculation app, the input shows up in the format `diff(f(x), x, a)`. I think it would be better if this could be done in the standard mathematical format, like on the Ti-84 Plus. This functionality already exists for inputting an integral, so I think it should be extended to derivatives as well.

#### Screenshots

This is what the derivative input looks like on the Ti-84 Plus CE:
![This is what the derivative input looks like on the Ti-84 Plus CE](https://user-images.githubusercontent.com/30819652/116009292-8d27b300-a5cd-11eb-9a9f-6f2504fbb937.png)

This is what the derivative input looks like on the NumWorks:
![numworks_derivative](https://user-images.githubusercontent.com/30819652/116009306-b0526280-a5cd-11eb-947e-cd2455acfde5.png)

The NumWorks integral input already uses the proper mathematical notation:
![numworks_integral](https://user-images.githubusercontent.com/30819652/116009333-db3cb680-a5cd-11eb-929b-0a31feaff8a2.png)

#### Describe the solution you'd like
I would like the NumWorks derivative input to use the proper mathematical notation, like on the Ti-84 Plus.

**Comment by RedGl0w** [comment] 2021-04-26 05:01
Duplicate of #1012

**Comment by artaxxx** [comment] 2021-04-26 07:37
Thanks, I close this issue since it's a duplicate. We are working on it!

**Closed by artaxxx** 2021-04-26 07:37 UTC
Labels: enhancement
