### ISSUE TITLE
Functions - Exact values in Table of values

### ISSUE THREAD

**Issue by XanderLeaDaren** [numworks/epsilon#1785] opened 2021-02-21 08:46 UTC
#### Problem you'd like to fix
When calculating images with a function involving e.g. fractions or surds, Epsilon displays approximate values instead of exact, although the Calculation app handles both.

#### Screenshots
Let’s define a function and ask for its table of values:
![screenshot_fonction](https://user-images.githubusercontent.com/28948599/108620016-3ebd3300-7429-11eb-803a-fd16f2f1bc9b.png) ![screenshot_tableau-actuel](https://user-images.githubusercontent.com/28948599/108620014-3d8c0600-7429-11eb-8ea7-c862810ea3a7.png)

#### Describe the solution you'd like
Display the exact value of the image, or even better the exact value and the approximate decimal value.
![screenshot_pour-proposition](https://user-images.githubusercontent.com/28948599/108620044-7e841a80-7429-11eb-985e-98f61215d445.png)

#### Describe alternatives you've considered
Using the Calculation app provides the exact values:
![screenshot_calculs-ok](https://user-images.githubusercontent.com/28948599/108620049-83e16500-7429-11eb-88ee-da2acf5ea8d9.png)

#### Additional context
İmpacts: simulator, physical device, phone app

**Comment by RedGl0w** [comment] 2021-02-21 08:52
Duplicate of #434

**Comment by artaxxx** [comment] 2021-02-22 11:58
Yes, it's something we want to do!
It's a duplicate so let me close this issue

**Closed by artaxxx** 2021-02-22 11:58 UTC
Labels: enhancement
