### ISSUE TITLE
Filesystem?

### ISSUE THREAD

**Issue by maximilianwalter** [numworks/epsilon#1513] opened 2020-04-12 20:44 UTC
This was probably suggested a lot but... 

I would suggest a filesystem or at least anything which makes installing third party applications easier.

As the calculator is more or less for highschool kids and tries to be as simple as possible (UX-wise), this would make things a lot easier. 

Obviously not everyone can build everything on his own and flash it. Something like TI Connect would be nice.

As I said, this was probably suggested a lot and maybe it's already planned (or declined?). Anyway, an answer would be appreciated:)

**Comment by MixedMatched** [comment] 2020-04-12 20:58
Currently, applications in Epsilon are linked into the binary as objects that call functions from other parts of the OS, so Epsilon doesn't natively have runtime-replaceable applications, because, AFAIK, applications are embedded instructions, not filesystem-adjacent files. The only "files" that exist in unmodified Epsilon are python scripts. 

*However*, there has been an unofficial attempt to resolve this, by @zardam, through the ["External" application](https://github.com/zardam/nw-external-apps ), which adds files and execution of runtime binaries. A native solution would be preferred, but I'm not exactly sure what that solution could be, besides what zardam uses (execution of an API-dependent binary from another application).

**Comment by Ecco** [comment] 2020-04-12 21:23
> I would suggest a filesystem or at least anything which makes installing third party applications easier.

Those are two different entirely different things.

Otherwise this is indeed a duplicate of #42. Closing as such 😄

**Closed by Ecco** 2020-04-12 21:23 UTC
Labels: enhancement
