### ISSUE TITLE
Calculator freezes when entering the formula '(x' in any application

### ISSUE THREAD

**Issue by EtienneProPvP** [numworks/epsilon#1881] opened 2021-09-27 17:33 UTC
#### Describe the bug

When I type in any application the formula '(x', the 'x' does not appear and the application loads. I can see it with the 'infinite' animation on the top right instead of the battery indicator.

This bug does not appear on the emulator.

I put you however a screenshot of what I want to write. I circled what does not appear.

However, if there is another character before the parenthesis, there is no problem.

Thank you for your understanding.

I wish you a good continuation for this great calculator.

Thank you.

#### Screenshots

![image](https://user-images.githubusercontent.com/91491763/134957196-b65f51d4-ecbf-48b0-b062-992083d9f484.png)

#### To Reproduce
1. Go to any app
2. Type '(' + 'var' with nothing before the parenthesis.
![image](https://user-images.githubusercontent.com/91491763/134969462-c9fdfbf0-8438-4885-8f51-642301d867af.png)
3. See error (infinite loading)

#### Expected behavior

I guess there shouldn't be this little problem when using this formula. xD

#### Environment
 - Epsilon version : 16.4.0
 - The platform(s) on which the problem happens: device.

**Comment by artaxxx** [comment] 2021-09-28 08:08
Thanks for your bug report. Could you please be more specific? I can't reproduce the bug. What are the steps to reproduce the bug from the reset?
Why does the status bar displays `shift` on your screenshot?

**Comment by MarkGhebrial** [comment] 2021-10-01 22:39
I am not able to reproduce this bug either

**Comment by EtienneProPvP** [comment] 2021-10-01 23:33
Good evening, I will try, this weekend, by resetting my calculator if the problem persists. If this turns out to be the case, I will explain the problem in more detail. thank you for your quick reply

**Comment by artaxxx** [comment] 2021-10-04 07:57
Let me close this issue since the bug doesn't seem reproductible. Feel free to reopen it if you find how to do

**Closed by artaxxx** 2021-10-04 07:57 UTC
