### ISSUE TITLE
Digit groupping in calculation results

### ISSUE THREAD

**Issue by MDLC01** [numworks/epsilon#1664] opened 2020-09-16 18:26 UTC
#### Problem you'd like to fix
When you're dealing with long results inside the calculation app, it can be quite difficult to read them.

#### Describe the solution you'd like
Grouping the digits 3 by 3 (separated with spaces) would solve this problem.

#### Screenshots
This is hard to read:
![hard_to_read](https://user-images.githubusercontent.com/57839069/93376352-c0e17400-f859-11ea-9436-92589a1116f3.png)
While this is easier to read:
![easier_to_read](https://user-images.githubusercontent.com/57839069/93376465-ea9a9b00-f859-11ea-9aae-0b81671c16f1.png)

#### Describe alternatives you've considered
Comas could also be used to separate groups of digits (instead of spaces). But spaces are preferable since they don't allow any confusion with the decimal separator.

#### Additional context
When copying the result, spaces (or comas) should **not** be copied.

**Comment by RedGl0w** [comment] 2020-09-16 18:30
Duplicate of #184

**Comment by artaxxx** [comment] 2021-07-22 09:41
Fixed in Version 16

**Closed by artaxxx** 2021-07-22 09:41 UTC
Labels: enhancement
