### ISSUE TITLE
type(enumerate()) Python code makes the calculator crash

### ISSUE THREAD

**Issue by sagessylu** [numworks/epsilon#1371] opened 2020-02-29 11:11 UTC
Executing the code `type(enumerate())` in the Python app makes the calculator crash.
This is an issue for both Python scripts and Python shell.
However, it works just fine if you put something between the brackets of `enumerate()`.

![screenshot](https://user-images.githubusercontent.com/49091098/75606029-14bc8380-5ae9-11ea-9c0c-c00d17a65cf0.png)
![screenshot(1)](https://user-images.githubusercontent.com/49091098/75606053-3d447d80-5ae9-11ea-9272-999b1676e0c4.png)

#### To Reproduce
1. Go to the Python app
2. Go to the Python shell
3. Type `type(enumerate())`
4. ⚠️ The calculator crashes

#### Expected behavior
It should print the same error as when you just run `enumerate()`

#### Environment
 - Epsilon version : 12.4.0
 - Works only on the real calculator (not the online simulator)

**Comment by RedGl0w** [comment] 2020-04-05 10:10
Seems to be patched with mpy 12 (tested with mpy 1.12.0)

**Comment by EmilieNumworks** [comment] 2020-04-06 11:22
Good catch @sagessylu. The bug is caused by a invalid memory reading; in `enumerate_make_new, we access `args[0]` even when `n_args = 0`... This was fixed in MicroPython source by this [https://github.com/micropython/micropython/commit/4ebbacd65eec4c0fde8ceb32274c06f5e3de3af6](commit) included in the version 1.12 (thanks @RedGl0w). We should definitely update the Micropython version embedded in Epsilon!

**Comment by RedGl0w** [comment] 2020-04-06 11:26
@EmilieNumworks this can be pached so with #1455 !

**Comment by EmilieNumworks** [comment] 2020-04-06 13:08
Done in #1457!

**Comment by Ecco** [comment] 2020-04-06 13:09
Well, #1457 hasn't been merged just yet…

**Comment by EmilieNumworks** [comment] 2020-04-06 13:13
Right, wrong button 😅

**Closed** 2020-04-07 09:34 UTC
