### ISSUE TITLE
Natural writing: fractions encompassing a product

### ISSUE THREAD

**Issue by Ecco** [numworks/epsilon#524] opened 2018-05-29 22:17 UTC
[Some user](https://www.reddit.com/r/numworks/comments/8n1f63/divisions_puissances_de_10/) said they would like it better if a fraction would encompass any preceding product.

In other words, typing in `2E3/6` currently outputs this:

![screenshot](https://user-images.githubusercontent.com/55989/40688516-b51f5184-639e-11e8-8164-67344b7b73f5.png)

The question is, wouldn't it be better if it would output this instead:

![screenshot-2](https://user-images.githubusercontent.com/55989/40688550-ca46d6a4-639e-11e8-919b-df0421223fb1.png)

What do you think?

**Comment by jacobly0** [comment] 2018-05-30 05:08
On other calculators, implicit multiplication has higher precedence than explicit * and / to allow you to do things like this, but I forget what poincare's current stance on implicit multiplication is.

**Comment by matheod** [comment] 2018-10-15 00:46
The issue is that we want 4 * 1/3 to be displayed as 4 * (1/3).

But I agree that 2 × 10^3/4 should be displayed as (2 × 10^3)/4.

So maybe 10^ should have a special behaviour ?

**Comment by artaxxx** [comment] 2019-01-11 10:30
This is fixed in 10.0.0

**Closed by artaxxx** 2019-01-11 10:30 UTC

**Comment by olaure01** [comment] 2019-04-05 17:16
Currently, ```2``` ```*10^x``` ```3``` ```/``` leads to:
![screenshot (1)](https://user-images.githubusercontent.com/30601497/55644745-139aad80-57d7-11e9-9f1b-2c796112a5e8.png)

According to the discussion above, wouldn't this be more natural:
![](https://user-images.githubusercontent.com/30601497/46922786-7bcdbb00-d00e-11e8-8a40-6b2a3a787528.png)
