### ISSUE TITLE
i wanted to have access to the epsilon 15 udpate

### ISSUE THREAD

**Issue by Philipou24** [numworks/epsilon#1908] opened 2021-12-07 16:54 UTC
ive upgraded Epsilon the the version 16 and dint know the consequences, now i wanted to have access to the Epsilon 15 upgrade if possible please, ill really apreciate it

![image_2021-12-07_175032](https://user-images.githubusercontent.com/94259154/145071430-fe30c640-a148-4c06-9d3c-d321d3943f49.png)

I really wanted to have access (via your website or any other way) to downgrade my Epsilon from version 16.4.0 to version 15

i just have one question just to know: why did you locked the installation of tier-part apps or firmware (like the periodic table, or the NES emulator, or Omega )  And i know that you don't want to give Epsilon 15 but if you could make an exeption _for_ _me_ , and ill really apreciate it! :)

![image_2021-12-07_175431](https://user-images.githubusercontent.com/94259154/145072074-fdc89612-ba63-4037-a5c1-0e0556e5f172.png)

**Comment by artaxxx** [comment] 2021-12-21 10:41
You'll find some information here: https://www.numworks.com/blog/secure-software-for-exams/

I'm also closing this issue since it's not a bug report or an enhancement we plan to do.

**Closed by artaxxx** 2021-12-21 10:41 UTC
Labels: enhancement

**Comment by Philipou24** [comment] 2021-12-21 10:50
But please it's very important

**Comment by borongyuan** [comment] 2022-03-20 08:32
This is a disappointing decision. Not all of your users are students who will use this calculator to take the exam. I bought this calculator because it's light and powerful, with an open system for engineering usage. Now the update has ruined it all, making it an unattractive product.
