### ISSUE TITLE
increasing the upper bound on integrals leads to incorrect values

### ISSUE THREAD

**Issue by AlexPMLikesNumWorks** [numworks/epsilon#894] opened 2019-02-09 20:17 UTC
(9.2.0, Calculus app)
incorrect integral calculations:
![screenshot-1000](https://user-images.githubusercontent.com/47484653/52525769-d7534100-2cae-11e9-885f-7591d543a1c1.png)-> correct value

![screenshot-8000](https://user-images.githubusercontent.com/47484653/52525780-f05bf200-2cae-11e9-99de-dab2473d149a.png)-> incorrect value

seems that increasing the upper bound in these integrals always breaks the computation

**Comment by AlexPMLikesNumWorks** [comment] 2019-02-09 22:10
OK, after a bit of reading looks like this one is a duplicate of #258

**Comment by Ecco** [comment] 2019-11-06 17:35
This is indeed a duplicate of #258. Closing as such.

**Closed by Ecco** 2019-11-06 17:35 UTC
