### ISSUE TITLE
Parenthesis + powers error in the Calculation app

### ISSUE THREAD

**Issue by Shadaki** [numworks/epsilon#1594] opened 2020-06-11 16:15 UTC
#### Describe the bug
When in the Calculation app, if you put an empty power (x^y) in a function like cos(), the left parenthesis of the function will not enlarge.

#### Screenshots
![screenshot](https://user-images.githubusercontent.com/49091098/84412068-fea57f80-ac0e-11ea-9204-87d0bf8444cd.png)

#### To Reproduce
1. Go to the Calculation app
2. Type the "cos" key, and then the "x^y" key
3. See error

#### Expected behavior
The left parenthesis should enlarge like for the right one.

#### Environment
 - Epsilon version : 13.2.0
 - Platform : All

**Comment by RedGl0w** [comment] 2020-07-29 14:02
The issue is that the left parenthese is the base of the power. The left parenthese needs to know the size of what is inside, but the power needs to know the size of the base. This creates an infinit loop, which is blocked by https://github.com/numworks/epsilon/blob/edafa0e15555bdd024660e78e36756651bd85438/poincare/src/bracket_layout.cpp#L105-L113
To avoid this, there's two solution :
- Add a specific case in the power layout : when the base is a parenthese, interpret the base with a default size
- Automaticaly replace the base layout, when it is a parenthese, to a empty layout

**Comment by artaxxx** [comment] 2022-11-25 10:01
Fixed in version 20

**Closed by artaxxx** 2022-11-25 10:01 UTC
