### ISSUE TITLE
Use BCD for calculations

### ISSUE THREAD

**Issue by Zezombye** [numworks/epsilon#43] opened 2017-08-31 09:16 UTC
I don't know why you've chosen floating point instead of BCD like Casio and TI, but there are issues that arise from that (see http://0.30000000000000004.com/).

If you type 0.1+0.2 it returns 0.3, but only because there isn't enough precision when displaying the result (there should be more precision btw). However if you type 0.1+0.2-0.3 it returns 2.775558e-17 instead of 0, and obviously a calculator that returns the wrong result isn't a good calculator.

The only solution that I know of is to use BCD for calculations.

**Comment by Ecco** [comment] 2017-08-31 10:14
This is indeed a good suggestion.

Currently Poincaré performs all its computations using IEEE754 floating point numbers. We aimed for consistency first, because there are quite a few cases (trigonometry for example) where it would need to use floating-point anyway.

That being said, we could definitely (and should) add an exact math engine.

**Comment by Zezombye** [comment] 2017-08-31 10:26
You don't need to use floating point for anything, Casio does trigonometry with BCD. Sure, floating point is faster, but BCD is fast enough for calculations (now, if you do something that requires real-time input like a game, you'd need to use floating point, but calculations require exact math and should always use BCD).

**Comment by Ecco** [comment] 2017-09-19 09:16
Indeed, but this issue is in fact a duplicate of #99.

**Closed by Ecco** 2017-09-19 09:16 UTC
Labels: enhancement
