### ISSUE TITLE
Numworks update not working on Opera, despite WebUSB support

### ISSUE THREAD

**Issue by bmuessig** [numworks/epsilon#1600] opened 2020-06-22 13:54 UTC
#### Describe the bug
I am not able to update a physical Numworks calculator through Opera, despite WebUSB support; even with a Google Chrome user agent set. I do not want to install Google Chrome - Google is not going to gain any administrative privileges on my computer. I just don't want to use that spyware browser.

#### Screenshots
![image](https://user-images.githubusercontent.com/2276327/85295584-70e45280-b4a0-11ea-96aa-b21a49be62bf.png)

#### To Reproduce
Use Opera and go to the Numworks update page.

#### Expected behavior
Opera should be able to update the calculator. If that's not possible, why are you not developing an offline update program as almost all other vendors did?!

**Comment by boricj** [comment] 2020-06-22 14:35
I would assume this is an [oversight](https://caniuse.com/#feat=webusb) in NumWorks' website. Do you have the same error message if you spoof the User-Agent in your web browser? You can also try [TI-Planet](https://ti-planet.github.io/webdfu_numworks/)'s WebDFU page or [Omega's web installer](https://getomega.web.app/install/latest) for online alternatives.

For an offline update, [it is possible](https://www.numworks.com/resources/engineering/software/build/) but it is more oriented for developers or power users than for everyday usage since it requires some setup and a CLI.

**Comment by bmuessig** [comment] 2020-06-22 14:45
Thanks for the quick response, boricj!

> spoof the User-Agent in your web browser
I did, as stated in my bug report, but unfortunately, that did not change anything.

> You can also try [TI-Planet](https://ti-planet.github.io/webdfu_numworks/)'s WebDFU page or [Omega's web installer](https://getomega.web.app/install/latest) for online alternatives.
TI-Planet's version shows a similar error, while Omega's installer appears to work.
I'd still much prefer, if Numworks could just fix their website and whitelist Opera and other compatible browsers.

> For an offline update, [it is possible](https://www.numworks.com/resources/engineering/software/build/) but it is more oriented for developers or power users than for everyday usage since it requires some setup and a CLI.
I just want to be a consumer this time and not always have to build and flash the software myself ;-)

**Comment by M4xi1m3** [comment] 2020-06-22 16:23
Omega's installer doesn't check for browser type, [it checks for support of WebUSB](https://github.com/Omega-Numworks/omega-numworks.github.io/blob/react-master/src/dfu/installer.js#L52). Maybe that's why it works despite the others not working. Can't explain for TI-Planet's WebDFU, as it checks in the same way as we do.

**Comment by bmuessig** [comment] 2020-06-22 16:47
> Can't explain for TI-Planet's WebDFU, as it checks in the same way as Omega installer does.

I'm sorry. TI-Planet's WebDFU appears to work too - I somehow overlooked the selection of the calculator model and only focused on the message below - stating that Google Chrome is required.

**Comment by Ecco** [comment] 2020-06-22 17:34
Actually we *purposedly* disabled Opera because they reported WebUSB support but their support was broken!

**Comment by bmuessig** [comment] 2020-06-22 17:39
> Actually we _purposedly_ disabled Opera because they reported WebUSB support but their support was broken!

A quick search by me did not turn up with any evidence that Opera has issues with WebUSB.

**Comment by Ecco** [comment] 2020-06-22 17:40
I just installed Opera's latest broken, and their WebUSB support seems completely broken on macOS: the device picker never shows up!

**Comment by Ecco** [comment] 2020-06-22 17:57
So to summarize, Opera always says it supports WebUSB (`navigator.usb` is defined) even though it sometimes doesn't. It might work on Windows, but it's definitely broken on macOS. As a result we can't trust what Opera says. And its market share doesn't justify us going through weird hoops to figure out when their support is actually present.

FYI, here's a snippet from the code we have:

```javascript
function hasWebUSB() {
  // WARNING: navigator.usb is defined on Opera browser but not fully working. */
  return (navigator.usb !== undefined && Platform.name != 'Opera')
}
```

We'd be happy to remove Opera from the blacklist as soon as they actually support WebUSB when they say they do. In the meantime, I'm going to close this issue because it unfortunately works as intended.

**Closed by Ecco** 2020-06-22 17:57 UTC

**Comment by bmuessig** [comment] 2020-06-22 18:05
> We'd be happy to remove Opera from the blacklist as soon as they actually support WebUSB when they say they do. In the meantime, I'm going to close this issue because it unfortunately works as intended.

The dialog happily shows up on Linux and Windows on the current versions of Opera.
It would be so easy to just make an exception for OS X:
```
function hasWebUSB() {
  // WARNING: navigator.usb is defined on Opera browser but not fully working on OS X. */
  if (Platform.name == 'Opera' && navigator.platform.includes('Mac'))
    return false;
  return (navigator.usb !== undefined);
}
```

**Comment by Ecco** [comment] 2020-06-22 18:07
Yeah, but if they can't get a simple dialog to show up, god only knows which other bugs there may be further down the road. And they don't even have a public bug tracker to report the issue on…

**Comment by bmuessig** [comment] 2020-06-22 18:10
There should be a manual "I know what I'm doing override"

**Comment by Ecco** [comment] 2020-06-22 18:13
Or Opera could fix their brower 😄

**Comment by bmuessig** [comment] 2020-06-22 18:14
https://workshop.numworks.com/devices/upgrade#iknowwhatimdoing ;-)

**Comment by boricj** [comment] 2020-06-22 18:15
While Opera doesn't have a public bug-tracker, it seems bug reports can nevertheless be submitted: https://help.opera.com/en/computer-bug-wizard/

**Comment by Ecco** [comment] 2020-06-22 18:18
I personally stopped filing bug into closed trackers as I've been `> /dev/null` too many times. But please be my guest 😄

**Comment by Ecco** [comment] 2020-06-23 17:53
Ok, we eventually allowed Opera on non-Mac platform! @bmuessig , you should be good to go 😄

**Comment by bmuessig** [comment] 2020-06-23 18:20
Thank you!!

**Comment by bmuessig** [comment] 2020-06-23 18:48
I've just performed a firmware update and it worked perfectly on Opera 64-bit on Windows 8.1.
