### ISSUE TITLE
Empty graph with sequence in graph app

### ISSUE THREAD

**Issue by RedGl0w** [numworks/epsilon#1783] opened 2021-02-15 14:18 UTC
#### Describe the bug
When defining `Un=n` and graphing `f(x)=Ux`, there's only the cursor on defined coordinates which is displayed, making the whole graph very strange... 

#### Expected behavior
There should be a point every defined Un (somehow like the graph in sequence) 

#### Screenshots
![image](https://user-images.githubusercontent.com/43498612/108719016-570f7980-751f-11eb-9bb2-f0efb2841dbe.png)
![image](https://user-images.githubusercontent.com/43498612/108719036-5ecf1e00-751f-11eb-9304-2db730a5d9a6.png)
![image](https://user-images.githubusercontent.com/43498612/108719049-655d9580-751f-11eb-96f4-0c26a31f2d26.png)

#### Environment
 - Epsilon master (v15)
 - The platform(s) on which the problem happens: all

**Comment by KarineNumWorks** [comment] 2024-12-16 16:55
I cannot reproduce this problem as it seems fixed. I will close this issue consequently !

**Closed by KarineNumWorks** 2024-12-16 16:55 UTC

**Comment by AngeDieu** [comment] 2025-01-04 11:37
I have the same poblem with Epsilon 23.2.5 (latest), so the problem is not solved.
Simply create a sequence in **sequence** app (for example u(n)=n ), the sequence is well ploted in sequence app.
Then go to **grapher** app ant create a function f(x) = u(n). The function defined only for integers creates doesn't plot, but it should plot a list of points (as in sequence app)
