### ISSUE TITLE
increasing the upper bound on integrals still leads to incorrect values

### ISSUE THREAD

**Issue by AlexPMLikesNumWorks** [numworks/epsilon#1183] opened 2019-11-06 14:11 UTC
(11.2.0, Calculus app)
incorrect integral calculations:
![52525769-d7534100-2cae-11e9-885f-7591d543a1c1](https://user-images.githubusercontent.com/47484653/68304943-129c6800-00a7-11ea-876a-e7ffaf0b9a28.png)-> correct value
![52525780-f05bf200-2cae-11e9-99de-dab2473d149a](https://user-images.githubusercontent.com/47484653/68304994-2cd64600-00a7-11ea-88c3-d174ab2950c3.png)-> incorrect value

It seems that increasing the upper bound in these integrals always breaks the computation

This bug has been reported 9 months ago  (#894) and even before (#258) but has been ignored since.
This behaviour (returning a blatantly incorrect result) should be avoided, either by fixing the integral approximation algorithm, or by detecting bad yields and rejecting them with an error message.

**Comment by Ecco** [comment] 2019-11-06 17:34
This is indeed a bug, but, as you said, it's been reported before. So I'll have to close this as  a duplicate of #894.

**Closed by Ecco** 2019-11-06 17:34 UTC
