### ISSUE TITLE
Underscore (i.e. "_") doesn't work in Python Shell as it does in MicroPython & Python3 interactive mode

### ISSUE THREAD

**Issue by mobluse** [numworks/epsilon#1907] opened 2021-12-05 16:00 UTC
#### Problem you'd like to fix
In Python3 and MicroPython v1.17 in interactive mode underscore "_" works as "last result"/"answer"/"ans", but this doesn't work in NumWorks Python shell.

#### Screenshots
![screenshot (6)](https://user-images.githubusercontent.com/5777329/144753671-8adee995-417f-473e-abac-d3f6d9f65dbf.png)

#### Describe the solution you'd like
That the same thing would happen as in Python3 or recent MicroPython i.e. `_` would store the result of the last calculation, so it could be used in the next. The Ans key isn't used now in the Python shell and that could perhaps be a shortcut to `_` independent of if `alpha`, `ALPHA`, or `shift` is on or off, just like x^y button types `**` in Python shell and editor.

#### Describe alternatives you've considered
I don't know in which version of MicroPython underscore as `Ans` was introduced, but maybe you removed it for a reason if it existed in 1.12. It would be interesting to know that reason.

#### Additional context
How it works in MicroPython for Linux:
```
MicroPython v1.17-134-gcb99ca986 on 2021-11-01; linux version
Use Ctrl-D to exit, Ctrl-E for paste mode
>>> 5+4
9
>>> _
9
>>> _+6
15
>>> _
15
>>> a=_
>>> a
15
>>> 
```

**Comment by RedGl0w** [comment] 2021-12-06 06:10
Seems to be a duplicate of https://github.com/numworks/epsilon/issues/259

**Comment by artaxxx** [comment] 2022-11-25 10:46
Duplicates #259

**Closed by artaxxx** 2022-11-25 10:46 UTC
Labels: enhancement
