### ISSUE TITLE
White text using draw_string isn't really white/invisible.

### ISSUE THREAD

**Issue by Afyu** [numworks/epsilon#1643] opened 2020-08-07 11:47 UTC
#### Describe the bug
Within the Python app, white text displayed using draw_string and the 'white' colour parameter doesn't really display a white text (depending on characters). The color is very light grey. Using (255,255,255) tuple instead of 'white' colour parameter doesn't fix the issue. This issue occurs on both simulator and calculator.

#### Screenshots
![Screen](https://user-images.githubusercontent.com/69348636/89641796-c343cc00-d8b2-11ea-851e-c83ecf3a531c.png)
![white_text](https://user-images.githubusercontent.com/69348636/89641683-824bb780-d8b2-11ea-9a54-bd75980b333d.png)

#### To Reproduce
1. Go to the Python app
2. In a script, type 
from kandinsky import *
draw_string("text to display",0,0,'white')
draw_string("second text to display",0,18,(255,255,255))
3. Execute the script
4. See error. Some characters are displayed in a very light grey colour which is not white.

#### Expected behavior
The displayed text is really white, then invisible.

#### Environment
 - Epsilon version 14.4.0 on both device and simulator.
 - The platform(s) on which the problem happens: both online simulator and actual device.

**Comment by sagessylu** [comment] 2020-08-16 08:54
This is works as intended: using varied colors to display a font is an old trick that makes the font look smoothier.
This is an unexpected consequence of that behavior, but it is unavoidable in my opinion.

**Comment by Ecco** [comment] 2020-08-24 20:31
This might indeed be due to antialiasing, but it still shouldn't happen nonetheless. Thanks for the bug report @Afyu !

**Comment by GabrielNumworks** [comment] 2020-08-25 08:17
Thanks for the report. This was indeed a problem with the method used to smoothly displays fonts : because of some faulty arithmetic, the program managed to find a colour gradient between two identical colours. Pull request #1650 fixes this issue.

**Comment by LeaNumworks** [comment] 2020-08-31 14:04
Closing, as #1650 was merged

**Closed by LeaNumworks** 2020-08-31 14:04 UTC
