### ISSUE TITLE
Bug plotting a function in python

### ISSUE THREAD

**Issue by fasfcastro** [numworks/epsilon#2241] opened 2024-10-02 16:20 UTC
#### Describe the bug

In the two python scripts below the first one works but the second fails and mathematically they are de same. See differences in the definition of f(x)

—- good script
from numpy import *
import matplotlib.pyplot as plt

def f(x):
return cos(x)*10.

x=linspace(0.1,0.5,50)

plt.plot(x,f(x))
plt.grid()
plt.show()

——- bad script
from numpy import *
import matplotlib.pyplot as plt

def f(x):
return 10.*cos(x)

x=linspace(0.1,0.5,50)

plt.plot(x,f(x))
plt.grid()
plt.show()

#### Environment
 - Epsilon version 23.2.5
 - The platform(s) on which the problem happens: only tried actual device

**Comment by fasfcastro** [comment] 2024-10-02 16:25
In the two python scripts below the first one works but the second fails and mathematically they are de same. See differences in the definition of f(x)

#### good on
# Type your text here
from numpy import *
import matplotlib.pyplot as plt


def f(x):
  return cos(x)*10.
  

x=linspace(0.1,0.5,50)

plt.plot(x,f(x))
plt.grid()
plt.show()

##### bad one
# Type your text here
from numpy import *
import matplotlib.pyplot as plt


def f(x):
  return 10.*cos(x)
  

x=linspace(0.1,0.5,50)

plt.plot(x,f(x))
plt.grid()
plt.show()


Thanks

**Comment by adri1numworks** [comment] 2024-10-09 09:27
This bug is already identified. A fix was proposed. Closed as duplicate of #2102

**Closed by adri1numworks** 2024-10-09 09:27 UTC
