### ISSUE TITLE
Double spaced lines in online Numworks Workshop editor

### ISSUE THREAD

**Issue by jccraig** [numworks/epsilon#1551] opened 2020-05-12 22:38 UTC
When I copy and paste (Ctrl-a Ctrl-c Ctrl-v) a program from IDLE or from Editplus (simple text editor) in my Windows 10 environment and into the NumWorks Workshop editor, the lines end up double-spaced.  I believe this is due to Windows text files using CRLF for end of lines, whereas Mac and Unix use either just CR or LF characters. 

As a temporary work-around for Windows users, the following code can be run to replace CRLF with just LF after copying NumWorks source code into the Windows clipboard. Then, a paste into the NumWorks Workshop edit window in the browser results in the desired single-spaced lines...
```
import pyperclip   # pip install pyperclip

CR = chr(13)
LF = chr(10)
CRLF = CR + LF

# Grab whatever text is in clipboard
s = pyperclip.paste()

# Replace all CRLF with LF
t=s.replace(CRLF, LF)

# Copy to the clipboard 
pyperclip.copy(t)
```

![zp1](https://user-images.githubusercontent.com/4132921/81752593-f7a01b80-946e-11ea-9867-4f7dbd58671c.png)
![zp2](https://user-images.githubusercontent.com/4132921/81752600-fa9b0c00-946e-11ea-910d-177d7cf0e404.png)

**Comment by jccraig** [comment] 2020-10-02 22:54
Is there any chance this issue will get resolved?  It's been months now, and it's still hassling me every time I edit offline on my Windows PC.  Thank you for taking a look!

**Comment by EmilieNumworks** [comment] 2020-10-05 08:13
Hello, I could not reproduce this on Windows 10 with editPlus (5.3 - build 2542) on Chrome and Internet Explorer. Could you please give us a hexfile of your clipboard content when you paste it in the Workshop editor?

**Comment by jccraig** [comment] 2020-10-05 16:13
Hi Emilie,

I created a small PDF containing screen grabs that show the problem with
greater clarity. Please see attached file.

Thank you,
John

**Comment by jccraig** [comment] 2020-10-05 16:14
I created a small PDF containing screen grabs that show the problem with greater clarity. Please see attached file.
[emilie.pdf](https://github.com/numworks/epsilon/files/5328607/emilie.pdf)

**Comment by EmilieNumworks** [comment] 2020-10-06 09:02
Thanks @jccraig for your clear explanations. I was able to reproduce your issue and find the origin of the problem. This should be fixed soon!

**Comment by jccraig** [comment] 2020-10-06 14:45
Thank you!

**Closed** 2020-10-07 21:26 UTC
