### ISSUE TITLE
Max values on KDColor components

### ISSUE THREAD

**Issue by RedGl0w** [numworks/epsilon#1363] opened 2020-02-26 21:04 UTC
#### Describe the bug
There's some max values on some KDColor components (For red : 248)

#### Exemple:
In python :
```py
fill_rect(0,0,320,240,(248,0,0))
a=get_pixel(100,100)
print(a[0])
```
In c++ :
```c++
std::cout << (int) KDColorRed.red() << std::endl;
```
Both will return 248

#### Expected behavior
I expected to have 255 returned ._.

#### Environment
 - Epsilonmaster
 - All

**Comment by Ecco** [comment] 2020-02-26 21:24
Yeah, KDColor is RGB565, by design. I don't think this is much of an issue though so I'm going to close this 😄

**Closed by Ecco** 2020-02-26 21:24 UTC

**Comment by RedGl0w** [comment] 2020-02-27 07:08
> Yeah, KDColor is RGB565, by design. I don't think this is much of an issue though so I'm going to close this smile

Some pupils or teachers, like https://github.com/cent20net, who reported me this issue, can find it weird, when they `fill_rect` in python, and get another color with `get_color()` ...

**Comment by Ecco** [comment] 2020-02-27 13:26
Well, yes, but the framebuffer *is* 16 bits. So there will be a loss of information at some point…

**Comment by RedGl0w** [comment] 2020-02-27 13:29
Maybe there's another solution...
