### ISSUE TITLE
Handle diacritics in the Python module

### ISSUE THREAD

**Issue by cent20net** [numworks/epsilon#1690] opened 2020-10-22 08:13 UTC
The calculator itselfs handles diacritics. It'd be great if the Python module handled diacritics, and the characters from the extended ASCII table.

**Comment by cent20net** [comment] 2020-10-22 08:22
Démo : https://workshop.numworks.com/python/cent20/test_ascii

**Comment by RedGl0w** [comment] 2020-10-22 08:55
Epsilon supports accents, but the `è` char is composed of `e` and `\``
See : https://github.com/numworks/epsilon/blob/c91c2a6e3fae7908ebe20952c6b3b6f61387a7bb/kandinsky/include/kandinsky/font.h#L11-L17

**Comment by Ecco** [comment] 2020-10-22 13:19
Hi @cent20net ! That's an interesting suggestion.

The big problem here is that there is no such a thing as *the* extended [ASCII table](https://en.wikipedia.org/wiki/Extended_ASCII).

ASCII only defines 128 characters. Then, people took advantage of the extra 8th bit in a byte to encode another group of 128 characters. But the problem is, different people used different conventions! So they each created their own extended ASCII tables: for example, for certain people, the number 192 meant `À`, and for other people that exact same number meant `Ŕ`. How can you possibly know what a 192 means when you read a text file then? Well, you can't, and that's a [nightmare](https://en.wikipedia.org/wiki/Extended_ASCII#Character_set_confusion).

Unicode solved that issue by assigning a unique number (called a codepoint) to every single character ever used. So as you can guess, there's a *lot* of them (IIRC, around 150 000). For example, `À` is 192 and `Ŕ` is 340.

Then, unicode suggested different ways to encode a sequence of codepoints into a sequence of bytes. The most popular one is by far UTF-8, which has the advantage of being compact and backward-compatible with ASCII.

We believe that the world should be using [UTF-8 everywhere](http://utf8everywhere.org/), so that's the option we used in the NumWorks calculator.

We actually do support UTF-8 in our Python code, but what you're asking for is in fact support for some form of extended ASCII. We don't want to support that ancient, fragile technology so I'm going to close this issue :smile:

PS: Also, we try and keep everything on our GitHub in english to make it easier for people from different countries 😄

**Closed by Ecco** 2020-10-22 13:19 UTC
Labels: enhancement

**Comment by cent20net** [comment] 2020-10-22 14:21
Hello Ecco,

I just did a new test.
https://workshop.numworks.com/python/cent20/test_accents

I just realized that accents are well managed on the python module, so certainly not with the python functions chr () and ord () but they are managed in the print () and draw_string ().

I was abused by a bug that I encountered in the past on the workshop coupled with a current bug on Omega IDE 😂 I therefore believed that it was not managed at all.

Sorry for the noise, I'm going back to develop my textual game on a graphic layer, in French so with accents!

Thanks for these explanations and this quick and enlightening answer, I even learned a trick for the extended ASCII table!
