### ISSUE TITLE
Calculation in verification mode

### ISSUE THREAD

**Issue by matheod** [numworks/epsilon#895] opened 2019-02-10 15:55 UTC
Student are lesser and lesser good at calculation. But when we look deeper, we see that they use too much calculator, stop doing step by step calculation, and use calculation even easy calculation (8/10, -3+2, etc.).

It would be nice to have a form of calculation in verification mode : 

Student write the calculation, then their answer, and the calculator tell them if they are right or wrong.

That might be a separate apps, or a special mode that would switch on the led in blue (fixed, no blinking).

**Comment by IonImpulse** [comment] 2019-02-13 00:50
This would be nice, but it seems like it would take up unnecessary space on the limited memory. Nevertheless, it sounds like an interesting idea.

**Comment by INailedIt** [comment] 2019-02-17 14:40
The calculator actually has that built into the calculation app. If you input the calculation then an equals sign followed by the answer the calculator will output `1` if it is true. Admittedly, this has the potential to be misinterpreted, so ideally the output should be `True` instead.

**Comment by RubenNumworks** [comment] 2020-03-06 16:31
Duplicate of #37

**Closed by RubenNumworks** 2020-03-06 16:31 UTC
Labels: enhancement
