### ISSUE TITLE
Exact form in functions app

### ISSUE THREAD

**Issue by INailedIt** [numworks/epsilon#886] opened 2019-02-01 18:22 UTC
Is there any way to have the functions app output the exact value instead of the approximate value on the graphing page? It'd be useful when dealing with radians and seeing things in terms of Pi.

**Comment by Ecco** [comment] 2019-03-15 20:56
Kind of similar to #434

**Comment by Ecco** [comment] 2019-10-07 18:19
Actually that's an exact duplicate of #434. Closing as such.

**Closed by Ecco** 2019-10-07 18:19 UTC
Labels: app-functions, enhancement
