### ISSUE TITLE
Compilation yields a bunch of warning at link time

### ISSUE THREAD

**Issue by SirCipherz** [numworks/epsilon#1060] opened 2019-09-03 17:38 UTC
The compilation ended with those errors :
``
ion/src/device/shared/stack.cpp:4:21: warning: type of '_stack_end' does not match original declaration [-Wlto-type-mismatch]
    4 | extern const void * _stack_end;
      |                     ^
ion/src/device/shared/usb/dfu_relocated.cpp:7:13: note: '_stack_end' was previously declared here
    7 | extern char _stack_end;
      |             ^
ion/src/device/n0110/drivers/board.cpp:8:15: warning: type of 'InitialisationVector' does not match original declaration [-Wlto-type-mismatch]
    8 | extern void * InitialisationVector;
      |               ^
ion/src/device/shared/boot/isr.c:15:5: note: 'InitialisationVector' was previously declared here
   15 | ISR InitialisationVector[INITIALISATION_VECTOR_SIZE]
      |     ^
``

**Comment by boricj** [comment] 2019-09-04 07:42
Are you sure the build actually failed? These are warnings, not errors, due to link-time optimization having issues with symbols declared in linker scripts. You should have an `epsilon.elf` file in your build directory.

**Comment by Ecco** [comment] 2019-09-04 08:59
Indeed, @boricj is most definitely right, those are warnings, not errors.

We should try to remove those warning at some point (IIRC they come from enabling LTO), but I gave it a shot a while ago and it wasn't straightforward.

**Comment by SirCipherz** [comment] 2019-09-04 18:05
That's errors because I can't do the next step

**Comment by madhatter0** [comment] 2019-09-08 09:26
Could you show us what happens when you try the next step?  This may be a duplicate of bugs already filed.

**Comment by Ecco** [comment] 2019-09-18 07:11
This is fixed by #1073

**Closed by Ecco** 2019-09-18 07:11 UTC
Labels: infra
