### ISSUE TITLE
[Poincare] sin function in radian mode behaves differently in Poincare and microPython

### ISSUE THREAD

**Issue by tarapitha** [numworks/epsilon#697] opened 2018-10-04 20:05 UTC
It is known that when x approaches zero then sin(x) approaches x. In microPython the answer to 
`sin(1.234567890123456E-15)` is `1.234567890123456E-15`

On the other hand, the same calculation in Poincare will yeld 0.

**Comment by Ecco** [comment] 2018-10-05 08:51
I'm sorry but I can't reproduce that issue. Closing.

![screenshot](https://user-images.githubusercontent.com/55989/46525671-8a88d500-c88c-11e8-9866-5a0a933f1354.png)

**Comment by madhatter0** [comment] 2018-10-05 08:59
For what it's worth, on my Numworks, running 1.7.0, in radians mode, I also get zero.

**Comment by LeaNumworks** [comment] 2018-10-05 09:08
There's indeed an issue on the device, and not in the simulator.

**Comment by EmilieNumworks** [comment] 2018-10-08 08:13
To compute sinus, we use the libc implementation of sinus which does have errors ([see here](https://www.gnu.org/software/libc/manual/html_node/Errors-in-Math-Functions.html)). However, this is not really connected to the first issue as Python also yields the approximate answer sin(3.14159265358)=9.7931777202935E-12.
What we could do is :
- find the expected error in order to avoid displaying the wrong digits
- simplify sin(pi+d) with the rule you gave provided that the user enters 'sin(p+1.2345678E-11)'. And the trigonometric simplification needs further improvements (more than just this one, I believe) ...
But both these improvements are other issues so I close this one for now.

**Closed by EmilieNumworks** 2018-10-08 08:13 UTC
