### ISSUE TITLE
Bricked after flash

### ISSUE THREAD

**Issue by GregBowyer** [numworks/epsilon#514] opened 2018-05-25 22:04 UTC
after the following

`make clean`
`make`
`sudo make epsilon_flash`

```
DFU     epsilon_flash
INFO    About to flash your device. Please plug your device to yo
        using an USB cable and press the RESET button the back of
DFU     epsilon_flash
dfu-util 0.8
Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc
Copyright 2010-2014 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to dfu-util@lists.gnumonks.org
dfu-util: Invalid DFU suffix signature
dfu-util: A valid DFU suffix will be required in a future dfu-uti
Opening DFU capable USB device...
ID 0483:df11
Run-time device DFU version 011a
Claiming USB DFU Interface...
Setting Alternate Setting #0 ...
Determining device status: state = dfuERROR, status = 10
dfuERROR, clearing status
Determining device status: state = dfuIDLE, status = 0
dfuIDLE, continuing
DFU mode device DFU version 011a
Device returned transfer size 2048
DfuSe interface name: "Internal Flash  "
Downloading to address = 0x08000000, size = 671540
Download    [=========================] 100%       671540 bytes
Download done.
File downloaded successfully
Transitioning to dfuMANIFEST state
```

Calculator is now dead, screen wont come on, stays in this update mode.
```
greg@gregslaptop ~/projects/epsilon $ sudo dfu-tool list
Found 0483:df11 [v34.0]:
 Mode:          DFU
 Status:        errFIRMWARE
 State:         dfuERROR
 ID:            0
  Name:         @Internal Flash  /0x08000000/04*016Kg,01*064Kg,07*128Kg
  Cipher:       none
  Region 0x00:  Zone:0, Sec#:0, Addr:0x08000000, Size:0x4000, Caps:0x7
  Region 0x01:  Zone:0, Sec#:0, Addr:0x08004000, Size:0x4000, Caps:0x7
  Region 0x02:  Zone:0, Sec#:0, Addr:0x08008000, Size:0x4000, Caps:0x7
  Region 0x03:  Zone:0, Sec#:0, Addr:0x0800c000, Size:0x4000, Caps:0x7
  Region 0x04:  Zone:0, Sec#:1, Addr:0x08000000, Size:0x10000, Caps:0x7
  Region 0x05:  Zone:0, Sec#:2, Addr:0x08000000, Size:0x20000, Caps:0x7
  Region 0x06:  Zone:0, Sec#:2, Addr:0x08020000, Size:0x20000, Caps:0x7
  Region 0x07:  Zone:0, Sec#:2, Addr:0x08040000, Size:0x20000, Caps:0x7
  Region 0x08:  Zone:0, Sec#:2, Addr:0x08060000, Size:0x20000, Caps:0x7
  Region 0x09:  Zone:0, Sec#:2, Addr:0x08080000, Size:0x20000, Caps:0x7
  Region 0x0a:  Zone:0, Sec#:2, Addr:0x080a0000, Size:0x20000, Caps:0x7
  Region 0x0b:  Zone:0, Sec#:2, Addr:0x080c0000, Size:0x20000, Caps:0x7
 ID:            1
  Cipher:       none
 ID:            2
  Cipher:       none
 ID:            3
  Cipher:       none
```

**Comment by jacobly0** [comment] 2018-05-26 03:26
I've had this happen when compiling with certain versions of gcc, which was always fixed by flashing an official release.

**Comment by Ecco** [comment] 2018-05-28 07:19
Hi @jacobly0, thanks for your help!

Hi @GregBowyer, could you eventually flash another firmware? Note that Epsilon is not involved when flashing a new firmware, we're using ST's USB DFU bootloader. I'm going to close this issue, feel free to reopen if needed.

**Closed by Ecco** 2018-05-28 07:19 UTC

**Comment by Lesquivemeau** [comment] 2018-09-23 10:06
Hi ! I had this problem too while trying to flash my fork, i have no problem updating via the workshop but flashing bricks the calculator every time i try, even with the official github repo

**Comment by Lesquivemeau** [comment] 2018-09-23 10:15
```
Found 0483:df11 [v34.0]:
 Protocol:      DfuSe
 Name:          STM32  BOOTLOADER
 Serial:        303F35403437
 Mode:          DFU
 Status:        errFIRMWARE
 State:         dfuERROR
 Transfer Size: 2,0 ko (2 048 octets)
 ID:            0
  Name:         Internal Flash
  Region 0x00:  Zone:0, Sec#:0, Addr:0x08000000, Size:0x4000, Caps:0x7 [REW]
  Region 0x01:  Zone:0, Sec#:0, Addr:0x08004000, Size:0x4000, Caps:0x7 [REW]
  Region 0x02:  Zone:0, Sec#:0, Addr:0x08008000, Size:0x4000, Caps:0x7 [REW]
  Region 0x03:  Zone:0, Sec#:0, Addr:0x0800c000, Size:0x4000, Caps:0x7 [REW]
  Region 0x04:  Zone:0, Sec#:1, Addr:0x08010000, Size:0x10000, Caps:0x7 [REW]
  Region 0x05:  Zone:0, Sec#:2, Addr:0x08020000, Size:0x20000, Caps:0x7 [REW]
  Region 0x06:  Zone:0, Sec#:2, Addr:0x08040000, Size:0x20000, Caps:0x7 [REW]
  Region 0x07:  Zone:0, Sec#:2, Addr:0x08060000, Size:0x20000, Caps:0x7 [REW]
  Region 0x08:  Zone:0, Sec#:2, Addr:0x08080000, Size:0x20000, Caps:0x7 [REW]
  Region 0x09:  Zone:0, Sec#:2, Addr:0x080a0000, Size:0x20000, Caps:0x7 [REW]
  Region 0x0a:  Zone:0, Sec#:2, Addr:0x080c0000, Size:0x20000, Caps:0x7 [REW]
  Region 0x0b:  Zone:0, Sec#:2, Addr:0x080e0000, Size:0x20000, Caps:0x7 [REW]
 ID:            1
  Name:         Option Bytes
  Region 0x00:  Zone:0, Sec#:0, Addr:0x1fffc000, Size:0x0010, Caps:0x3 [RW]
 ID:            2
  Name:         OTP Memory
  Region 0x00:  Zone:0, Sec#:0, Addr:0x1fff7800, Size:0x0200, Caps:0x3 [RW]
  Region 0x01:  Zone:0, Sec#:1, Addr:0x1fff7a00, Size:0x0010, Caps:0x3 [RW]
 ID:            3
  Name:         Device Feature
  Region 0x00:  Zone:0, Sec#:0, Addr:0xffff0000, Size:0x0004, Caps:0x3 [RW]
```

After successful workshop update -> disconnect -> connect -> reset, still errored

**Comment by adriweb** [comment] 2018-09-23 10:31
dfu-util may be a bit weird sometimes, try https://devanlai.github.io/webdfu/dfu-util/ with a binary you built

**Comment by Lesquivemeau** [comment] 2018-09-23 10:44
Tried to flash with this site, however it don't work, i'm gonna try it from my win partition

**Comment by adriweb** [comment] 2018-09-23 10:50
I’d expect more issues with windows than anything else... it works directly on Mac and should be ok on Linux once you have the permissions set.

**Comment by Lesquivemeau** [comment] 2018-09-23 10:51
It should.

**Comment by matheod** [comment] 2018-09-23 12:07
I am using this issue to ask this question : is it possible to brick the calculator or are we safe to flash aanything ?

**Comment by Lesquivemeau** [comment] 2018-09-23 12:15
Normally you are safe, as you can't overwrite the bootloader in any way

**Comment by Ecco** [comment] 2018-09-24 07:30
The bootloader is non-overwriteable, so bricking the calculator is virtually impossible 😄

**Comment by Lesquivemeau** [comment] 2018-11-17 19:39
The problem is definitely gcc, as it happens only with versions i compiled myself.

I retried from a fresh insta: same
I currently use gcc 5.4.0 20160609

Now, if i install gcc-6 from ppa and try with `make CXX=gcc-6` the build fails with multiples errors:

`
gcc-6: warning: ‘-mcpu=’ is deprecated; use ‘-mtune=’ or ‘-march=’ instead
gcc-6: error: unrecognized command line option ‘-mthumb’; did you mean ‘-mtbm’?
gcc-6: error: unrecognized command line option ‘-mfloat-abi=hard’
gcc-6: error: unrecognized command line option ‘-mfpu=fpv4-sp-d16’
`

Huh, i'm stuck...

**Comment by boricj** [comment] 2018-11-17 20:09
Are you trying to build a firmware for the NumWorks calculator target with your host compiler? That won't work, you need an ARM cross-compiler. Check out https://www.numworks.com/resources/engineering/software/sdk/ and especially the manual setup section.

**Comment by Lesquivemeau** [comment] 2018-11-23 14:41
Problem solved using a fresh ubuntu install, just try and change distro.
See #772
