### ISSUE TITLE
Fractions with decimals only output decimals

### ISSUE THREAD

**Issue by INailedIt** [numworks/epsilon#887] opened 2019-02-01 18:25 UTC
I'm fairly certain this has been asked before but is there any way to still show the fractional result with this, as well as the decimal.

**Comment by boricj** [comment] 2019-02-01 20:17
Decimal numbers are assumed to be imprecise. If I want to convert a finite decimal number to a fraction, I'd just multiply and divide:

![image](https://user-images.githubusercontent.com/9872969/52147052-d6466200-2665-11e9-9f49-5ae8a819ed02.png)

It won't work with repeating decimals, but calculators can't work with an infinite number of digits...

**Comment by INailedIt** [comment] 2019-02-02 21:33
That's fair I guess. However, surely there'd be a way to recognise if a number is recurring and represent that? Even, Casio's cheapest calculators can do that.

**Comment by AlainBusser** [comment] 2019-02-04 04:50
So should a calculator transform 3.141514151555 into a fraction ? How many recurring decimals would you need to consider a number as a fraction ? The problem is not that easy I guess. 

I would prefer a function linking a number (in decimal notation) to its nearest Farey fraction, say with an order of 1e6 by default. As long as the number is not really transformed into a fraction. This would allow one to understand that 0.1 and 0.01 are **not** floats and still be able to retrieve their decimal values 1/10 and 1/100.

To compute the nearest Farey fraction, one can efficiently use [the Stern-Brocot_tree](https://en.wikipedia.org/wiki/Stern-Brocot_tree). The algorithm converges quickly (it goes like dichotomy but instead of computing the average of the two bouds, one just computes their [mediant](https://en.wikipedia.org/wiki/Mediant_(mathematics)) )

**Comment by INailedIt** [comment] 2019-02-04 22:05
Firstly, Pi is not recurring. Secondly, using Farey Sequences is an interesting idea. And lastly, my point about recurring digits is that it'd be nice to be able to use the symbol instead of using fractions or spamming the pattern.

**Comment by INailedIt** [comment] 2019-02-04 22:20
Actually, couldn't this be used to have accurate values in the functions, equations, regression... apps?

**Comment by FrnchFrgg** [comment] 2019-05-15 10:42
It seems this issue is a duplicate of #713, maybe some of the insights here could be put there and this issue closed ?

**Comment by RubenNumworks** [comment] 2020-03-06 16:14
Since version 11 of Epsilon, selecting an approximate result makes the exact fractional result appear.

As for the point about numbers with recurring digits, it is already reported in issue #869.

**Closed by RubenNumworks** 2020-03-06 16:14 UTC
