### ISSUE TITLE
Absolute value of subtraction of 2 random numbers is sometimes negative

### ISSUE THREAD

**Issue by wblondel** [numworks/epsilon#2040] opened 2023-03-24 18:15 UTC
#### Describe the bug
The absolute value of subtraction of 2 random numbers is sometimes negative.

#### Screenshots
![screenshot (1)](https://user-images.githubusercontent.com/7508531/227606763-b04bc7ee-bcae-427a-ace2-c95a86940781.png)

#### To Reproduce
1. Go to the 'Calculation' app
2. Type `abs(random()-random())`
3. See error

#### Expected behavior
Absolute values should not be negative.

#### Environment
 - Epsilon version (Settings > About > Software version): 20.4.0
 - The platform(s) on which the problem happens: online simulator

**Comment by goualard-f** [comment] 2023-03-25 18:01
The same happens with only one call to `random()`:

![screenshot](https://user-images.githubusercontent.com/26631692/227733895-c09e0acb-fbf8-4c9e-a215-d7b3bc362737.png)

**Comment by pitonyak** [comment] 2023-09-15 23:05
I cannot reproduce this on 21.2.0 (Running on my Hardware) or 22.2.2 (web browser version), 22.2.1 (version I biult on my Fedora Linux computer and run using "make PLATFORM=simulator epsilon_run"). 

I used git log on absolute_value.cpp and it shows the last commit (at least on main) to be from Feb 21, so, before the bug report. 

Am I missing something?

**Comment by wblondel** [comment] 2023-09-16 17:42
I am not able to reproduce the issue on version 21.2.2 (web version downloaded from numworks.com).

I checked the files and just like you @pitonyak I don't know what fixed the issue 😅

**Comment by EmilieNumworks** [comment] 2023-09-18 08:35
This was fixed by this [commit](https://github.com/numworks/epsilon/commit/ca97ddf0e19e942acf0a817722093c26172d8e50) in version-21.
Thanks for reporting!

**Closed by EmilieNumworks** 2023-09-18 08:35 UTC
