### ISSUE TITLE
Circular list

### ISSUE THREAD

**Issue by Salamandar** [numworks/epsilon#588] opened 2018-06-26 13:09 UTC
When inside a list (toolbox, scripts list, …), an expected behaviour is to go from the top to the bottom of the list by clicking the "up arrow" (and the other way around of course).

**Comment by 0b101** [comment] 2018-06-26 13:45
#39

**Comment by Ecco** [comment] 2018-06-26 13:56
Indeed, that's a duplicate of #39. Closing 😄

**Closed by Ecco** 2018-06-26 13:56 UTC

**Comment by Salamandar** [comment] 2018-06-26 14:05
Woops, I didn't have the correct keywords when searching for duplicate.
