### ISSUE TITLE
poor text quality

### ISSUE THREAD

**Issue by nityanand86876** [numworks/epsilon#1976] opened 2022-09-16 08:29 UTC
#### Describe the bug
A clear and concise description of what the bug is. Please describe a **single** bug per issue. Feel free to create multiple issues though!

#### Screenshots
Please provide at least one screenshot of the issue happening. This is by far the best way to quickly show any issue! To attach a screenshot, just go to our [online simulator](https://www.numworks.com/simulator), navigate to reproduce your issue, and click the "screenshot" button. Then drag'n'drop the file here!

#### To Reproduce
1. Go to the '...' app
2. Type '....'

#### Environment
 - Epsilon version (Settings > A
![Screenshot from 2022-09-16 13-58-49](https://user-images.githubusercontent.com/85880458/190593580-1649dab9-e6d1-4a9a-b541-75db907f95aa.png)
bout > Software version).
 - The platform(s) on which the problem happens: online simulator, actual device, etc...
poor text quality occur on gui mode

**Comment by artaxxx** [comment] 2022-09-16 08:48
I close this issue since it doesn't provide enough information to reproduce the problem. Feel free to open a new one with a precise description if the problem persists.

**Closed by artaxxx** 2022-09-16 08:48 UTC
