### ISSUE TITLE
Even by following the tutorial, I am unable to compile epsilon.

### ISSUE THREAD

**Issue by HastagGuigui** [numworks/epsilon#1890] opened 2021-10-18 19:12 UTC
#### Describe the bug
Epsilon doesn't compile when writing "make" like written in the last section of the website's tutorial

#### Screenshots
![image](https://user-images.githubusercontent.com/47950669/137791807-a1cd9818-9c04-45a8-bb7f-6dde8b75104e.png)
(Sorry in advance, I have my Linux language set to French, but it says that it cannot find the bootloader makefile)

#### To Reproduce
1. Follow the tutorial
2. This error happens when doing the section "Run Epsilon on your calculator"

#### Expected behavior
Epsilon would compile and I would be prompted to reset and all that

#### Environment
 - Epsilon version: github (Last commit: 3 september
 - The platform(s) on which the problem happens: Command prompt, while compiling for an actual device

**Comment by matteoturini** [comment] 2021-11-10 20:18
Same issue. Ubuntu 18.04. Issue appears on `master` and `version-16` branch.

**Comment by RedGl0w** [comment] 2021-11-10 20:33
Somehow duplicate of https://github.com/numworks/epsilon/issues/1873

**Comment by matteoturini** [comment] 2021-11-11 13:06
@HastagGuigui La calculatrice n'est plus open source. Numworks a fait une decision de bloquer les firmwares customizés.

**Closed** 2021-11-11 13:08 UTC
