### ISSUE TITLE
Error with float in ploting function (with x)

### ISSUE THREAD

**Issue by RedGl0w** [numworks/epsilon#1171] opened 2019-10-27 20:47 UTC
#### Describe the bug
When you draw f(x)=x , and then you go back to x=-1,2, and then you go to 0, when you arrive to x=0,4 and you go right, it makes x=-1.1102E-16

#### Screenshots
![image](https://user-images.githubusercontent.com/43498612/67641576-24417b00-f903-11e9-92e6-038c53b3acc3.png)
![image](https://user-images.githubusercontent.com/43498612/67641595-46d39400-f903-11e9-9dbd-c06d579dea59.png)
![image](https://user-images.githubusercontent.com/43498612/67641582-34595a80-f903-11e9-887a-5bd7fd75d856.png)
![image](https://user-images.githubusercontent.com/43498612/67641585-3a4f3b80-f903-11e9-89b4-13bbfcfb81fb.png)

#### Expected behavior
I would expect to have x=0 and y=0

#### Environment
 - Epsilon version : 12.0.0
 - The platform(s) on which the problem happens: simulator and actual devices

**Comment by nsajko** [comment] 2020-03-02 00:32
Seems this is fixed in current master.

**Comment by Ecco** [comment] 2020-03-02 20:37
I can't reproduce this either so I'm going to close it. Feel free to reopen if this ever pops up again 😄

**Closed by Ecco** 2020-03-02 20:37 UTC
