### ISSUE TITLE
Web simulator have issue with dead key

### ISSUE THREAD

**Issue by matheod** [numworks/epsilon#618] opened 2018-07-21 18:21 UTC
Try pressing the ^ it will output a matrix (because it detect a ], which seem illogical because it should be [ but anyway)

If double pressing ^, it detect a ] and a ^.

Good luck :D

**Comment by Ecco** [comment] 2019-03-15 21:00
Actually, that's a duplicate of #617

**Closed by Ecco** 2019-03-15 21:00 UTC
Labels: bug, platform-emscripten
