### ISSUE TITLE
region `RAM_BUFFER' overflowed and others with DEBUG=1

### ISSUE THREAD

**Issue by x893** [numworks/epsilon#1591] opened 2020-06-07 09:51 UTC
Hello,
thanks for your awesome project !
I build debug version under debian with command
**make DEBUG=1 PLATFORM=device MODEL=n0100**
and see error

LD      ion/src/device/shared/usb/dfu.elf
/usr/lib/gcc/arm-none-eabi/7.3.1/../../../arm-none-eabi/bin/ld: output/debug/device/n0100/ion/src/device/shared/usb/dfu.elf section `.text' will not fit in region `RAM_BUFFER'
/usr/lib/gcc/arm-none-eabi/7.3.1/../../../arm-none-eabi/bin/ld: region `RAM_BUFFER' overflowed by 20128 bytes
/usr/lib/gcc/arm-none-eabi/7.3.1/../../../arm-none-eabi/bin/ld: output/debug/device/n0100/ion/src/device/shared/usb/stack/endpoint0.o: in function `Ion::Device::USB::Endpoint0::readAndDispatchSetupPacket()':
/mnt/f/Downloads/numworks/epsilon/ion/src/device/shared/usb/stack/endpoint0.cpp:111: undefined reference to `Ion::Device::USB::Endpoint0::MaxTransferSize'
/usr/lib/gcc/arm-none-eabi/7.3.1/../../../arm-none-eabi/bin/ld: output/debug/device/n0100/ion/src/device/shared/usb/stack/endpoint0.o: in function `Ion::Device::USB::Endpoint0::receiveSomeData()':
/mnt/f/Downloads/numworks/epsilon/ion/src/device/shared/usb/stack/endpoint0.cpp:271: undefined reference to `Ion::Device::USB::Endpoint0::k_maxPacketSize'
collect2: error: ld returned 1 exit status
make: *** [build/rules.mk:77: output/debug/device/n0100/ion/src/device/shared/usb/dfu.elf] Error 1

if i use
**make DEBUG=0 PLATFORM=device MODEL=n0100**
all build normally.
Can you help with LD (or other) file ?

Thanks in advance
Mitek

P.S. I check for n0110 and see the some problem
**make DEBUG=1 PLATFORM=device MODEL=n0110**

LD      ion/src/device/shared/usb/dfu.elf
/usr/lib/gcc/arm-none-eabi/7.3.1/../../../arm-none-eabi/bin/ld: output/debug/device/n0110/ion/src/device/shared/usb/dfu.elf section `.text' will not fit in region `RAM_BUFFER'
/usr/lib/gcc/arm-none-eabi/7.3.1/../../../arm-none-eabi/bin/ld: region `RAM_BUFFER' overflowed by 21296 bytes
/usr/lib/gcc/arm-none-eabi/7.3.1/../../../arm-none-eabi/bin/ld: output/debug/device/n0110/ion/src/device/shared/usb/stack/endpoint0.o: in function `Ion::Device::USB::Endpoint0::readAndDispatchSetupPacket()':
/mnt/f/Downloads/numworks/epsilon/ion/src/device/shared/usb/stack/endpoint0.cpp:111: undefined reference to `Ion::Device::USB::Endpoint0::MaxTransferSize'
/usr/lib/gcc/arm-none-eabi/7.3.1/../../../arm-none-eabi/bin/ld: output/debug/device/n0110/ion/src/device/shared/usb/stack/endpoint0.o: in function `Ion::Device::USB::Endpoint0::receiveSomeData()':
/mnt/f/Downloads/numworks/epsilon/ion/src/device/shared/usb/stack/endpoint0.cpp:271: undefined reference to `Ion::Device::USB::Endpoint0::k_maxPacketSize'
collect2: error: ld returned 1 exit status
make: *** [build/rules.mk:77: output/debug/device/n0110/ion/src/device/shared/usb/dfu.elf] Error 1

and
**make DEBUG=0 PLATFORM=device MODEL=n0110**
build without errors.

**Comment by Ecco** [comment] 2020-06-07 19:29
Unfortunately this one works as intended. The hardware isn't powerful enough to load a full-debug build.

**Comment by x893** [comment] 2020-06-07 21:57
I found next way to resolve debug build with n0110 model:
1.   in dfu.ld change
  RAM_BUFFER (rw) : ORIGIN = EPSILON_STACK_END, LENGTH = **11K**
2. in config.mk remove all except en
  EPSILON_I18N ?= **en**
3. in defaults.mk change to
  ifeq ($(DEBUG),1)
    SFLAGS += **-O1** -g
    **SFLAGS += -DNDEBUG**
  else

Now i can debug firmware with Ozone.
Thanks for you project

**Comment by Ecco** [comment] 2020-07-10 00:26
Thanks! I'm going to close this issue because it works as intended 😄

**Closed by Ecco** 2020-07-10 00:26 UTC
