### ISSUE TITLE
Manually change the color of functions/sequences

### ISSUE THREAD

**Issue by Flirno** [numworks/epsilon#1247] opened 2019-12-13 21:08 UTC
Currently the color of the functions and sequences we plot are random.
I think it would be a good to add the option to  **change the color of the functions** we plot in the function app :) (and also in the sequence app ofc)

- Like for instance if we want to differentiate derivatives from their primitives, it would be easier to differentiate them.

- Or also if you want to create 1 function out of 2/3/... functions (a function defined by parts), then put them both at the same color ;)

- etc.

In direct acces in this menu : 
![screenshot (5)](https://user-images.githubusercontent.com/34623058/70831913-16cd4b00-1df4-11ea-9ab2-bfb15ba6c191.png)
![screenshot (6)](https://user-images.githubusercontent.com/34623058/70831914-17fe7800-1df4-11ea-8cf7-6ef67ed7c9fd.png)

Thank you for reading :)

**Comment by suazhero** [comment] 2019-12-18 08:43
Colors aren't really random, are they? f red, g blue, h green etc...

**Comment by Flirno** [comment] 2019-12-19 06:38
Yes [they are](https://i.imgur.com/cfaryJP.jpg)  :/

**Comment by suazhero** [comment] 2019-12-19 06:47
Well, if colors are always the same for f, g, h etc... They're not random... But nevermind I get your point. You want to be able to customize the colors. 
But they're definitely not random, and having always the same colors as currently implemented allows to immediately identify which one is f, g, h... By habit

**Comment by MixedMatched** [comment] 2019-12-22 22:56
@suazhero not exactly. They don't correspond to letter function. The color sequence starts at the beginning of a "session" of running the functions app, by which I mean the app isn't reset by a flash or crash, but the letter function corresponds to the existence of functions with names in the name sequence. All of that essentially means that you can create a few functions (f, g, etc.) that will correspond to what you assume are the normal functions, but if you delete your original f(x) and create a new one, it will be named f(x), but it will have a different color.

**Comment by suazhero** [comment] 2019-12-23 09:21
Oh right. Didn't notice that. Never actually removed f or g... But changed the content instead. Thx.

**Comment by RubenNumworks** [comment] 2020-03-12 10:52
Duplicate of #931

**Comment by artaxxx** [comment] 2022-06-06 11:58
Fixed in 19.0.0

**Closed by artaxxx** 2022-06-06 11:58 UTC
Labels: enhancement
