### ISSUE TITLE
format the result's display

### ISSUE THREAD

**Issue by erwanh1** [numworks/epsilon#228] opened 2017-10-26 12:36 UTC
Could it be possible to display resultats by grouping digits by 3 so 1500.2568 will be displayed 1 500.256 8?

**Comment by Ecco** [comment] 2017-11-06 20:50
Hi @erwanh1 ! This is a duplicate of #184, so I'm closing this issue. It's still very useful though, since it let us know that more people are interested in this functionality, so thanks for reporting this!

**Closed by Ecco** 2017-11-06 20:50 UTC
