### ISSUE TITLE
Why does Numworks make Python a toy instead of a tool?

### ISSUE THREAD

**Issue by woailafang** [numworks/epsilon#1941] opened 2022-03-29 13:53 UTC
Python is a great helper for my work. I bought this calculator with the expectation that its 8MB ROM and 256KB memory can store and run Python scripts well. But the actual device is: it only provides 32KB to store python files, running a script larger than 8KB would crash the RAM with a "memory error",and the ridiculous WebUSB additionally. ....Why does Numworks make Python a toy instead of a tool?

**Comment by Ecco** [comment] 2022-03-29 17:52
Duplicate of #1547

**Closed by Ecco** 2022-03-29 17:52 UTC
Labels: enhancement
