### ISSUE TITLE
'make' will fail after commit 8264e3: "Enable LTO for the device".

### ISSUE THREAD

**Issue by tarapitha** [numworks/epsilon#742] opened 2018-10-21 06:04 UTC
I noticed that 'make' will fail on linking, starting from commit 8264e3 from Oct 10 (Enable LTO for the device), while 'make PLATFORM=simulator' will run successfully.

If 'LTO = 0' is inserted into 'build/toolchain.arm-gcc.mak' then 'make' will produce working firmware.

I've tested the building with similar results with SDK on Devuan 2.0.0 and Raspbian 9.

**Comment by EmilieNumworks** [comment] 2018-10-22 07:45
Hi,
It might be caused by the compiler version. You should try compiling with the last GNU Arm Embedded Toolchain (that you can get from [here](https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads)).

**Comment by Ecco** [comment] 2018-10-24 07:46
I'm going to close this as this is most likely due to an older toolchain. Feel free to reopen if the issue arises on the latest ARM toolchain.

**Closed by Ecco** 2018-10-24 07:46 UTC
